#!/bin/sh

PIDFILE="$(dirname "$0")/PID"

if [ -f $PIDFILE ]; then
	if (kill -15 $(cat $PIDFILE) &> /dev/null); then
		echo "Server terminated successfully!" >&2
		rm -f $PIDFILE
		exit 0
	else
		echo "Failed terminating server with SIGTERM, please check and manually kill PID $(cat $PIDFILE)" >&2
		exit 2
	fi
else
	echo "PIDFILE not found" >&2
	exit 1
fi
